# Generated by Django 5.0.10 on 2026-04-23 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_visitor_actual_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('daily_capacity_limit', models.PositiveIntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitorapproval',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('section_type', models.CharField(choices=[('general', 'General Area'), ('restricted', 'Restricted Area'), ('lab', 'Laboratory'), ('server', 'Server Room'), ('executive', 'Executive Floor'), ('conference', 'Conference Room'), ('other', 'Other')], default='general', max_length=20)),
                ('daily_capacity', models.PositiveIntegerField(default=50)),
                ('requires_escort', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='account.location')),
            ],
            options={
                'ordering': ['location__site__name', 'location__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='account.site'),
        ),
        migrations.CreateModel(
            name='CooldownPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_type', models.CharField(choices=[('daily', 'Daily Recurring'), ('one_time', 'One Time'), ('emergency', 'Emergency')], default='one_time', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('start_time', models.TimeField(blank=True, help_text='For daily cooldowns', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='For daily cooldowns', null=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cooldowns', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldowns', to='account.site')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='visitor',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='account.site'),
        ),
        migrations.CreateModel(
            name='VisitorSectionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required if status is rejected')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_sections', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_approvals', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_approvals', to='account.section')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_section_approvals', to='account.visitor')),
            ],
            options={
                'ordering': ['section__location__site__name', 'section__location__name', 'section__name'],
            },
        ),
        migrations.AddField(
            model_name='visitor',
            name='approved_sections',
            field=models.ManyToManyField(related_name='approved_visitors', through='account.VisitorSectionApproval', to='account.section'),
        ),
        migrations.CreateModel(
            name='VisitorSectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Why this section is needed')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_sections', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_requests', to='account.section')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_requests', to='account.visitor')),
            ],
            options={
                'ordering': ['section__location__site__name', 'section__location__name', 'section__name'],
            },
        ),
        migrations.AddField(
            model_name='visitor',
            name='requested_sections',
            field=models.ManyToManyField(related_name='requested_visitors', through='account.VisitorSectionRequest', to='account.section'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['site'], name='account_vis_site_id_4d0b17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('location', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('site', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='visitorsectionapproval',
            unique_together={('visitor', 'section', 'approver')},
        ),
        migrations.AlterUniqueTogether(
            name='visitorsectionrequest',
            unique_together={('visitor', 'section')},
        ),
    ]
