# Generated by Django 5.0.10 on 2026-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_location_site_alter_employee_id_alter_visitor_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorsectionapproval',
            options={'ordering': ['section__name']},
        ),
        migrations.AlterModelOptions(
            name='visitorsectionrequest',
            options={'ordering': ['section__name']},
        ),
        migrations.AddField(
            model_name='visitorsectionapproval',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
