# Generated by Django 5.0.10 on 2026-04-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_visitorsectionapproval_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSectionTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_check_in', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('section_check_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Time spent in this section in minutes')),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('check_in_notes', models.TextField(blank=True)),
                ('check_out_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_checkins', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_checkouts', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_trackings', to='account.section')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_trackings', to='account.visitor')),
            ],
            options={
                'ordering': ['section__name'],
                'indexes': [models.Index(fields=['visitor', 'status'], name='account_vis_visitor_18be96_idx'), models.Index(fields=['section_check_in'], name='account_vis_section_a35304_idx'), models.Index(fields=['section_check_out'], name='account_vis_section_bbaada_idx')],
                'unique_together': {('visitor', 'section')},
            },
        ),
    ]
