# Generated by Django 5.0.10 on 2026-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_visitorsectiontracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("partially_approved", "Partially Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
