# Generated by Django 5.0.10 on 2026-04-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_visitorapproval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorsectionapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
