# Generated by Django 5.0.10 on 2026-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_visitorsectionapproval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="photo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="photo",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="visitor_photos/"
            ),
        ),
    ]
