# Generated by Django 5.0.10 on 2026-04-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("approval_request", "Approval Request"),
                    ("approval_response", "Approval Response"),
                    ("visitor_checkin", "Visitor Check-in"),
                    ("system", "System Notification"),
                ],
                max_length=100,
            ),
        ),
    ]
