# Generated by Django 6.0.4 on 2026-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="actual_arrival_time",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="actual_departure_time",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="expected_arrival_time",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="expected_departure_time",
        ),
        migrations.AddField(
            model_name="visitor",
            name="actual_check_in",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="actual_check_out",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="check_in_notes",
            field=models.TextField(blank=True, help_text="Notes taken during check-in"),
        ),
        migrations.AddField(
            model_name="visitor",
            name="check_out_notes",
            field=models.TextField(
                blank=True, help_text="Notes taken during check-out"
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="designated_check_in",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="designated_check_out",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="early_arrival_minutes",
            field=models.IntegerField(
                default=0, help_text="Minutes early for check-in"
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="host_department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="visitor",
            name="late_arrival_minutes",
            field=models.IntegerField(default=0, help_text="Minutes late for check-in"),
        ),
        migrations.AddField(
            model_name="visitor",
            name="meeting_room",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="visitor",
            name="overtime_minutes",
            field=models.IntegerField(
                default=0, help_text="Minutes stayed beyond designated check-out"
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="visit_duration_minutes",
            field=models.IntegerField(
                default=0, help_text="Actual visit duration in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("partially_approved", "Partially Approved"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("no_show", "No Show"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["designated_check_in"], name="account_vis_designa_66e268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["designated_check_out"], name="account_vis_designa_6f1a42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["actual_check_in"], name="account_vis_actual__f69497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["actual_check_out"], name="account_vis_actual__4c15d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["status"], name="account_vis_status_2bc79c_idx"),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["designated_check_in", "status"],
                name="account_vis_designa_fbbb09_idx",
            ),
        ),
    ]
